# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-09 19:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('location', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('date', models.DateTimeField()),
                ('fb_id', models.CharField(default='', max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='FAQ',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.CharField(max_length=300)),
                ('answer', models.TextField()),
                ('list_position', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Gallery',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='GalleryImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('file', models.ImageField(upload_to=b'')),
            ],
        ),
        migrations.CreateModel(
            name='JobPosting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('company_name', models.CharField(max_length=300)),
                ('company_blurb', models.TextField()),
                ('company_url', models.CharField(max_length=300)),
                ('location', models.CharField(max_length=300)),
                ('expiration_date', models.DateField()),
                ('contact_email', models.EmailField(max_length=254)),
                ('approved', models.BooleanField(default=False)),
            ],
        ),
        migrations.CreateModel(
            name='Membership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('description', models.TextField()),
                ('price', models.CharField(max_length=300)),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300)),
                ('email', models.EmailField(max_length=254)),
                ('message', models.TextField()),
                ('created', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.CreateModel(
            name='MessageType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('list_position', models.IntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Officer',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name_first', models.CharField(max_length=300, verbose_name='First Name')),
                ('name_last', models.CharField(max_length=300, verbose_name='Last Name')),
                ('photo', models.ImageField(upload_to='officer_photos')),
                ('bio', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='OfficerRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=300)),
                ('list_position', models.IntegerField()),
                ('email', models.EmailField(max_length=254)),
            ],
        ),
        migrations.AddField(
            model_name='officer',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shpesfba.OfficerRole'),
        ),
        migrations.AddField(
            model_name='messagetype',
            name='responsible_officer_role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shpesfba.OfficerRole'),
        ),
        migrations.AddField(
            model_name='message',
            name='message_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='shpesfba.MessageType'),
        ),
    ]
