# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-07 18:15
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shpesfba', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='messagetype',
            old_name='tite',
            new_name='title',
        ),
    ]
