# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-10-22 22:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('shpesfba', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='galleryimage',
            name='file',
        ),
        migrations.AddField(
            model_name='gallery',
            name='date_created',
            field=models.DateField(null=True),
        ),
        migrations.AddField(
            model_name='gallery',
            name='description',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='galleryimage',
            name='caption',
            field=models.CharField(blank=True, max_length=300),
        ),
        migrations.AddField(
            model_name='galleryimage',
            name='full_size_image',
            field=models.ImageField(null=True, upload_to=b''),
        ),
        migrations.AddField(
            model_name='galleryimage',
            name='gallery',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='images', to='shpesfba.Gallery'),
        ),
        migrations.AddField(
            model_name='galleryimage',
            name='thumbnail_image',
            field=models.ImageField(blank=True, null=True, upload_to=b''),
        ),
    ]
