# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-13 20:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shpesfba', '0002_auto_20161022_1541'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='eventbrite_id',
            field=models.CharField(blank=True, default='', max_length=300),
        ),
    ]
