# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-08 00:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shpesfba', '0002_auto_20160807_1115'),
    ]

    operations = [
        migrations.AddField(
            model_name='event',
            name='fb_id',
            field=models.CharField(default='', max_length=300),
        ),
    ]
