# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2017-09-13 20:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shpesfba', '0003_event_eventbrite_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='event',
            old_name='eventbrite_id',
            new_name='eventbrite_url',
        ),
    ]
