# -*- coding: utf-8 -*-
# Generated by Django 1.10 on 2016-08-08 00:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shpesfba', '0003_event_fb_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobposting',
            name='company_url',
            field=models.CharField(max_length=300),
        ),
    ]
